### PR TITLE
dm-writeboost-target.c: Fix build error in 6.10

### LINKED ISSUE #256: module build fails for Linux 6.10
```
/var/lib/dkms/dm-writeboost/2.2.17/build/dm-writeboost-target.c: In function 'dm_devsize':
/var/lib/dkms/dm-writeboost/2.2.17/build/dm-writeboost-target.c:119:37: error: 'struct block_device' has no member named 'bd_inode'
  119 |         return i_size_read(dev->bdev->bd_inode) >> 9;
      |                                     ^~
```

The corresponding Linux commit is https://github.com/torvalds/linux/commit/203c1ce0bb063d1620698e39637b64f2d09c1368 "RIP ->bd_inode" in v6.10-rc1.

### PR DESCRIPTION
**Pull request by WestonReed**
`bdev->bd_inode` was removed in 6.10; replace it with `bdev_nr_sectors`

See kernel commit: https://github.com/torvalds/linux/commit/203c1ce0bb063d1620698e39637b64f2d09c1368

Closes #256

### CODE REVIEW

File: src/dm-writeboost-target.c [hunk 1]
```diff
@@ -116,7 +116,11 @@ int wb_io_internal(struct wb_device *wb, struct dm_io_request *io_req,
 
 sector_t dm_devsize(struct dm_dev *dev)
 {
+#if LINUX_VERSION_CODE < KERNEL_VERSION(6, 10, 0)
 	return i_size_read(dev->bdev->bd_inode) >> 9;
+#else
+    return bdev_nr_sectors(dev->bdev);
+#endif
```
Comment (WestonReed) [inline src/dm-writeboost-target.c:123]: `bdev_nr_sectors` was [added in 5.11](https://elixir.bootlin.com/linux/v5.11-rc1/A/ident/bdev_nr_sectors), so we could switch this to build with 5.11+ kernels instead. I'm unsure what the best practice here is though.

File: src/dm-writeboost-target.c [hunk 2]
```diff
@@ -116,7 +116,11 @@ int wb_io_internal(struct wb_device *wb, struct dm_io_request *io_req,
 
 sector_t dm_devsize(struct dm_dev *dev)
 {
+#if LINUX_VERSION_CODE < KERNEL_VERSION(6, 10, 0)
 	return i_size_read(dev->bdev->bd_inode) >> 9;
+#else
+	return bdev_nr_sectors(dev->bdev);
+#endif
```
Comment (WestonReed) [inline src/dm-writeboost-target.c:123]: `bdev_nr_sectors` was [added in 5.11](https://elixir.bootlin.com/linux/v5.11-rc1/A/ident/bdev_nr_sectors), so we could switch this to build with 5.11+ kernels instead. I'm unsure what the best practice here is though.

Comment (akiradeveloper) [reply src/dm-writeboost-target.c:123]: @WestonReed Thank you for the PR.

Not sure this is the best practice in the community though, I think the switch boundary should be 5.11 to make the code more informative: your suggestion here seems to me that `bdev_nr_sectors` was introduced in 6.10.

**Review by akiradeveloper — CHANGES_REQUESTED** [review]

**Comment by WestonReed** [comment]
@akiradeveloper Makes sense - I've added another commit to use 5.11 as the switch instead.
