### ISSUE TITLE
Unable to compile with 4.15

### ISSUE THREAD

**Issue by akiradeveloper** [akiradeveloper/dm-writeboost#189]
This is reported by user

```
db-02 /home/evk/dm-writeboost/src # make all
make -C /lib/modules/4.15.1-gentoo/build M=/home/evk/dm-writeboost/src
modules
make[1]: Entering directory '/usr/src/linux-4.15.1-gentoo'
  CC [M]  /home/evk/dm-writeboost/src/dm-writeboost-target.o
/home/evk/dm-writeboost/src/dm-writeboost-target.c: In function
‘reserve_read_cache_cell’:
/home/evk/dm-writeboost/src/dm-writeboost-target.c:785:7: error: implicit
declaration of function ‘ACCESS_ONCE’
[-Werror=implicit-function-declaration]
  if (!ACCESS_ONCE(wb->read_cache_threshold))
       ^~~~~~~~~~~
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:317:
/home/evk/dm-writeboost/src/dm-writeboost-target.o] Error 1
make[1]: *** [Makefile:1508: _module_/home/evk/dm-writeboost/src] Error 2
make[1]: Leaving directory '/usr/src/linux-4.15.1-gentoo'
make: *** [Makefile:11: all] Error 2
```

**Comment by onlyjob** [comment]
Any progress? Thanks.

**Comment by akiradeveloper** [comment]
Once 4.17 is officially released, I will release 2.2.9 with this fix.

**Comment by akiradeveloper** [comment]
fixed in v2.2.9
